#  Some questions to understand python Basics

In [1]:
import pandas as pd
import numpy as np

1. Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line.
Hints: Consider use range(#begin, #end) method


In [2]:
l=list()
for x in range(2000,3201):
    if x%7==0:
        if x%5!=0:
            l.append(x)
print(l)

[2002, 2009, 2016, 2023, 2037, 2044, 2051, 2058, 2072, 2079, 2086, 2093, 2107, 2114, 2121, 2128, 2142, 2149, 2156, 2163, 2177, 2184, 2191, 2198, 2212, 2219, 2226, 2233, 2247, 2254, 2261, 2268, 2282, 2289, 2296, 2303, 2317, 2324, 2331, 2338, 2352, 2359, 2366, 2373, 2387, 2394, 2401, 2408, 2422, 2429, 2436, 2443, 2457, 2464, 2471, 2478, 2492, 2499, 2506, 2513, 2527, 2534, 2541, 2548, 2562, 2569, 2576, 2583, 2597, 2604, 2611, 2618, 2632, 2639, 2646, 2653, 2667, 2674, 2681, 2688, 2702, 2709, 2716, 2723, 2737, 2744, 2751, 2758, 2772, 2779, 2786, 2793, 2807, 2814, 2821, 2828, 2842, 2849, 2856, 2863, 2877, 2884, 2891, 2898, 2912, 2919, 2926, 2933, 2947, 2954, 2961, 2968, 2982, 2989, 2996, 3003, 3017, 3024, 3031, 3038, 3052, 3059, 3066, 3073, 3087, 3094, 3101, 3108, 3122, 3129, 3136, 3143, 3157, 3164, 3171, 3178, 3192, 3199]


2. Write a program which can compute the factorial of a given numbers. The results should be printed in a comma-separated sequence on a single line.
Suppose the input is supplied to the program: 8
Then, the output should be: 40320
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [1]:
#n=input("Enter n:")
n=8
n=int(n)
x=1
while n>1:
        x=x*n
        n=n-1
print(x)

40320


3. With a given integral number n, write a program to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included) and then the program should print the dictionary.
Suppose the input is supplied to the program: 8
Then, the output should be: {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}
Hints: In case of input data being supplied to the question, it should be assumed to be a console input. Consider use dict()


In [2]:
#n=int(input("Enter n:"))
n=int(8)
d={i:i**2 for i in range(1,n+1)}
print(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


#### 4. Write a program which accepts a sequence of comma-separated numbers from console and generate a list and a tuple which contains every number.
Suppose the input is supplied to the program: 34, 67, 55, 33, 12, 98
Then, the output should be:
['34', '67', '55', '33', '12', '98']
('34', '67', '55', '33', '12', '98')
Hints: In case of input data being supplied to the question, it should be assumed to be a console input. tuple() method can convert list to tuple

In [4]:
#x=input()
x='34,67,55,33,12,98'
x=list(x.split(','))
print(x,tuple(x))

['34', '67', '55', '33', '12', '98'] ('34', '67', '55', '33', '12', '98')


5. Define a class which has at least two methods:
getString: to get a string from console input
printString: to print the string in upper case
    Also please include simple test function to test the class methods.
Hints: Use __init__ method to construct some parameters

In [6]:
class string:
    str=''
    def __init__(self):
        str=''
    
    def getstring(self):
        self.str=input("Enter a string:")
    
    def printstring(self):
        x=self.str.upper()
        print(x)
    
    def test(self):
        self.getstring()
        self.printstring()

In [7]:
s=string()

In [8]:
s.test()

Enter a string:hello world!
HELLO WORLD!


6. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 * C * D)/H]
Following are the fixed values of C and H: C is 50. H is 30.
D is the variable whose values should be input to your program in a comma-separated sequence.
Let us assume the following comma separated input sequence is given to the program: 100,150,180
The output of the program should be: 18, 22, 24
Hints: If the output received is in decimal form, it should be rounded off to its nearest value (for example, if the output received is 26.0, it should be printed as 26)
In case of input data being supplied to the question, it should be assumed to be a console input.


In [9]:
C=50
H=30
i=input("Enter numbers:")
D=list(i.split(','))
D
l=[]
for x in D:
    Q=(2*C*int(x))/H
    l.append(round(Q))
print(l)

Enter numbers:100,150,180
[333, 500, 600]


7. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
Note: i=0,1.., X-1; j=0,1,¡Y-1.
Suppose the following inputs are given to the program: 3, 5
Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]
Hints: In case of input data being supplied to the question, it should be assumed to be a console input in a comma-separated form.


In [13]:
X=int(input())
Y=int(input())
arr=np.zeros([X,Y])
for i in range(X):
    for j in range(Y):
        arr[i][j]=i*j
print(arr)

3
5
[[0. 0. 0. 0. 0.]
 [0. 1. 2. 3. 4.]
 [0. 2. 4. 6. 8.]]


8. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.
Suppose the input is supplied to the program: without, hello, bag, world
Then, the output should be: bag, hello, without, world
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [14]:
x=input()
l=x.split(',')
l.sort()
l


hello,bag,world


['bag', 'hello', 'world']

9. Write a program that accepts sequence of lines as input and prints the lines after making all characters in the sentence capitalized.
Suppose the input is supplied to the program: Hello world
Practice makes perfect
Then, the output should be: HELLO WORLD
PRACTICE MAKES PERFECT
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [15]:
str=input()
print(str.upper())

Hello World
HELLO WORLD


10. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.
Suppose the input is supplied to the program: hello world and practice makes perfect and hello world again
Then, the output should be: again and hello makes perfect practice world
Hints: In case of input data being supplied to the question, it should be assumed to be a console input. We use set container to remove duplicated data automatically and then use sorted() to sort the data.


In [16]:
str=list(input().split(' '))
x=list(set(str))
x.sort()
print(x)


hello world and practice makes perfect and hello world
['and', 'hello', 'makes', 'perfect', 'practice', 'world']


11. Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
Suppose the input is supplied to the program: 0100,0011,1010,1001
Then the output should be: 1010
Notes: Assume the data is input by console.
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.


In [17]:
io=input().split(',')
l=[]
for x in io:
    if int(x)%5==0:
        l.append(int(x))
l

0100,0011,1010,1001


[100, 1010]

12. Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number.
The numbers obtained should be printed in a comma-separated sequence on a single line.
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [25]:
l=input().split(',')
ls=[]
for x in l:
    l=0
    for y in x:
        if int(y)%2!=0:
            l=1
    if l==0:
        ls.append(int(x))
print(ls)
        

10,20
[20]


13. Write a program that accepts a sentence and calculate the number of letters and digits.
Suppose the input is supplied to the program: hello world! 123
Then, the output should be: LETTERS 10
DIGITS 3
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.


In [26]:
m=input()
l=0
d=0
for x in m:
    if x.isdigit():
        d=d+1
    elif x.isalpha():
        l=l+1
print("Letters {} Digits {}".format(l,d))

hello world!123
Letters 10 Digits 3


14. Write a program that accepts a sentence and calculate the number of upper case letters and lower case letters.
Suppose the input is supplied to the program: Hello world!
Then, the output should be: UPPER CASE 1
LOWER CASE 9
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.


In [27]:
m=input()
u=0
l=0
for x in m:
    if x.isupper():
        u=u+1
    elif x.islower():
        l=l+1
print("UPPER CASE {} LOWER CASE {}".format(u,l))

Hello World!
UPPER CASE 2 LOWER CASE 8


15. Write a program that computes the value of a+aa+aaa+aaaa with a given digit as the value of a.
Suppose the input is supplied to the program: 9
Then, the output should be: 11106
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.


In [29]:
n=int(input())
x=n+(n*11)+(n*111)+(n*1111)
x

9


11106

#### 16. Use a list comprehension to square each odd number in a list. The list is input by a sequence of comma-separated numbers.
Suppose the input is supplied to the program: 1,2,3,4,5,6,7,8,9
Then, the output should be: 1, 3, 5, 7, 9
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.


In [32]:
l=input().split(',')
ls=[int(x) for x in l if int(x)%2!=0]
ls
    

1,2,3,4,5,6,7,8,9


[1, 3, 5, 7, 9]

17. Write a program that computes the net amount of a bank account based a transaction log from console input. The transaction log format is shown as following:
D 100
W 200
--D means deposit while W means withdrawal.
Suppose the input is supplied to the program:
D 300
D 300
W 200
D 100
Then, the output should be: 500
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.



In [33]:
l=input().split(' ')
l1=l[::2]
l2=l[1::2]
D=0
W=0
d=zip(l1,l2)
for x,y in d:
    if x=='D':
        D=D+int(y)
    else:
        W=W+int(y)
print(D-W)

D 300 D 300 W 200 D 100
500


18. A website requires the users to input username and password to register. Write a program to check the validity of password input by users.
Following are the criteria for checking the password:
 1. At least 1 letter between [a-z] 
 2. At least 1 number between [0-9]
 3. At least 1 character from [$#@]
 4. Minimum length of transaction password: 6
 5. Maximum length of transaction password: 12
Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.
If the following passwords are given as input to the program: ABd1234@1,a F1#,2w3E*,2We3345
Then, the output of the program should be: ABd1234@1
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.



In [34]:
pwd=input().split(',')
ls=[]
for y in pwd:
    a=0
    n=0
    s=0
    for x in y:
        if x.isalpha():
            a=a+1
        elif x.isdigit():
            n=n+1
        elif (x=='$') or (x=='@') or (x=='#'):
            s=s+1
    l=len(y)
    if (a>0) and (n>0) and (s>0) and (l<12) and (l>5):
        ls.append(y)
ls


ABd1234@1,a F1#,2w3E*,2We3345


['ABd1234@1']

19. You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
1: Sort based on name;
2: Then sort based on age;
3: Then sort by score.
The priority is that name > age > score.
If the following tuples are given as input to the program:
Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85
Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
Hints: In case of input data being supplied to the question, it should be assumed to be a console input. We use itemgetter to enable multiple sort keys.


In [35]:
from operator import itemgetter, attrgetter

l = []
while True:
    s = input()
    if not s:
        break
    l.append(tuple(s.split(",")))

print(sorted(l, key=itemgetter(0,1,2)))

Tom,19,80
John,20,90
Jony,17,91
Jony,17,93
Json,21,85

[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]


20. Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.
Hints: Consider use yield


In [36]:
def putNumbers(n):
    i = 0
    while i<n:
        j=i
        i=i+1
        if j%7==0:
            yield j

for i in putNumbers(100):
    print(i)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


21. A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps. The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2
¡The
numbers after the direction are steps. Please write a program to compute the distance from current position after a sequence of movement and original point. If the distance is a float, then just print the nearest integer.
If the following tuples are given as input to the program:
UP 5
DOWN 3
LEFT 3
RIGHT 2
Then, the output of the program should be: 2
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [37]:
import math
pos = [0,0]
while True:
    s = input()
    if not s:
        break
    movement = s.split(" ")
    direction = movement[0]
    steps = int(movement[1])
    if direction=="UP":
        pos[0]+=steps
    elif direction=="DOWN":
        pos[0]-=steps
    elif direction=="LEFT":
        pos[1]-=steps
    elif direction=="RIGHT":
        pos[1]+=steps
    else:
        pass

print(int(round(math.sqrt(pos[1]**2+pos[0]**2))))

UP 5
DOWN 3
LEFT 3
RIGHT 2

2


22. Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically.
Suppose the input is supplied to the program:
New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3.
Then, the output should be:
2:2
3.:1
3?:1
New:1
Python:5
Read:1
and:1
between:1
choosing:1
or:2
to:1
Hints: In case of input data being supplied to the question, it should be assumed to be a console input.

In [38]:
freq = {}
line = input()
for word in line.split():
    freq[word] = freq.get(word,0)+1

words = freq.keys()
words = [(k, freq[k]) for k in sorted(freq)]

for w in words:
    print(w)

 New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3
('2', 2)
('3', 1)
('3?', 1)
('New', 1)
('Python', 5)
('Read', 1)
('and', 1)
('between', 1)
('choosing', 1)
('or', 2)
('to', 1)


23. Write a method which can calculate square value of number
Hints: Using the ** operator


In [39]:
def square(n):
    return n**2
x=square(4)
print(x)

16


24. Python has many built-in functions, and if you do not know how to use it, you can read document online or find some books. But Python has a built-in document function for every
built-in functions. Please write a program to print some Python built-in functions documents, such as abs(), int(), raw_input() And add document for your own function
Hints: The built-in document method is __doc__


In [40]:
print(abs.__doc__)
print(int.__doc__)
print(input.__doc__)

def square(num):
    '''
    Return the square value of the input number.
    
    The input number must be integer.
    '''
    return num ** 2

print(square(4))
print(square.__doc__)


Return the absolute value of the argument.
int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4
Forward raw_input to frontends

        Raises
        ------
        StdinNotImplentedError if active frontend doesn't support stdin.
        
16

    Return the square value of the input number.
    
    The input number must be integer.
    


25. Define a class, which have a class parameter and have a same instance parameter.
Hints: Define a instance parameter, need add it in __init__ method
You can init a object with construct parameter or set the value later


In [41]:
class Person:
    name = "Person"
    
    def __init__(self, name = None):
        self.name = name

jeffrey = Person("Jeffrey")
print("%s name is %s" % (Person.name, jeffrey.name))

nico = Person()
nico.name = "Nico"
print("%s name is %s" % (Person.name, nico.name))


Person name is Jeffrey
Person name is Nico


26. Define a function which can compute the sum of two numbers.
Hints: Define a function with two numbers as arguments. You can compute the sum in the function and return the value.


In [42]:
def sum(a,b):
    return a+b
print(sum(2,3))

5


27. Define a function that can convert a integer into a string and print it in console.
Hints: Use str() to convert a number to string.


In [10]:
def convert(a):
    a=str(a)
    print(a)
convert(123)

123


28. Define a function that can convert a integer into a string and print it in console.
Hints: Use str() to convert a number to string.


In [11]:
def convert(a):
    a=str(a)
    print(a)
convert(123)

123


29. Define a function that can receive two integral numbers in string form and compute their sum and then print it in console.
Hints: Use int() to convert a string to integer.


In [53]:
def sumstr(str):
    x,y=str.split(',')
    print(int(x)+int(y))
sumstr('2,3')


5


30. Define a function that can accept two strings as input and concatenate them and then print it in console.
Hints: Use + to concatenate the strings


In [54]:
def concat(s1,s2):
    print(s1+s2)
concat('Hello ','World')

Hello World


31. Define a function that can accept two strings as input and print the string with maximum length in console. If two strings have the same length, then the function should print al l strings line by line.
Hints: Use len() function to get the length of a string


In [55]:
def big(s1,s2):
    if len(s1)>len(s2):
        print(s1)
    elif len(s1)<len(s2):
        print(s2)
    else:
        print(s1,s2)
big('hello','world!')

world!


32. Define a function that can accept an integer number as input and print the "It is an even number" if the number is even, otherwise print "It is an odd number".
Hints: Use % operator to check if a number is even or odd.


In [56]:
def mod2(a):
    if a%2==0:
        print('It is an even number')
    else:
        print("It is an odd number")
mod2(3)

It is an odd number


33. Define a function which can print a dictionary where the keys are numbers between 1 and 3 (both included) and the values are square of keys.
Hints: Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number

In [57]:
def printdict():
    d=dict()
    d[1]=1
    d[2]=2**2
    d[3]=3**2
    print(d)
printdict()

{1: 1, 2: 4, 3: 9}


34. Define a function which can print a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys.
Hints: Use dict[key]=value pattern to put entry into a dictionary.
Use ** operator to get power of a number. Use range() for loops.


In [58]:
def printdict():
    d=dict()
    for x in range(1,21):
        d[x]=x**2
    print(d)
printdict()

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225, 16: 256, 17: 289, 18: 324, 19: 361, 20: 400}


35. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the values only.
Hints: Use dict[key]=value pattern to put entry into a dictionary. Use ** operator to get power of a number. Use range() for loops. Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.


In [59]:
def printdict():
    d=dict()
    for x in range(1,21):
        d[x]=x**2
    for k,v in d.items():
        print(v)
printdict()

1
4
9
16
25
36
49
64
81
100
121
144
169
196
225
256
289
324
361
400


36. Define a function which can generate a dictionary where the keys are numbers between 1 and 20 (both included) and the values are square of keys. The function should just print the keys only.
Hints: Use dict[key]=value pattern to put entry into a dictionary. Use ** operator to get power of a number. Use range() for loops. Use keys() to iterate keys in the dictionary. Also we can use item() to get key/value pairs.


In [60]:
def printdict():
    d=dict()
    for x in range(1,21):
        d[x]=x**2
    for k,v in d.items():
        print(k)
printdict()

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


37. Define a function which can generate and print a list where the values are square of numbers between 1 and 20 (both included).
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list.


In [61]:
def printlist():
    l=[]
    for x in range(1,21):
        l.append(x**2)
    print(l)
printlist()

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


38. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the first 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list


In [62]:
def printlist():
    l=[]
    for x in range(1,21):
        l.append(x**2)
    print(l[:5])
printlist()

[1, 4, 9, 16, 25]


39. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print the last 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list

In [63]:
def printlist():
    l=[]
    for x in range(1,21):
        l.append(x**2)
    print(l[-5:])
printlist()

[256, 289, 324, 361, 400]


40. Define a function which can generate a list where the values are square of numbers between 1 and 20 (both included). Then the function needs to print all values except the first 5 elements in the list.
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use [n1:n2] to slice a list


In [64]:
def printlist():
    l=[]
    for x in range(1,21):
        l.append(x**2)
    print(l[5:])
printlist()

[36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


41. Define a function which can generate and print a tuple where the value are square of numbers between 1 and 20 (both included).
Hints: Use ** operator to get power of a number. Use range() for loops. Use list.append() to add values into a list. Use tuple() to get a tuple from a list.


In [65]:
def printlist():
    l=[]
    for x in range(1,21):
        l.append(x**2)
    l=tuple(l)
    print(l[5:])
printlist()

(36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400)


42. With a given tuple (1,2,3,4,5,6,7,8,9,10), write a program to print the first half values in one line and the last half values in one line.
Hints: Use [n1:n2] notation to get a slice from a tuple.


In [66]:
l=tuple(range(1,11))
print(l[:5])
print(l[5:])

(1, 2, 3, 4, 5)
(6, 7, 8, 9, 10)


43. Write a program to generate and print another tuple whose values are even numbers in the given tuple (1,2,3,4,5,6,7,8,9,10).
Hints: Use "for" to iterate the tuple. Use tuple() to generate a tuple from a list.


In [67]:
l=tuple(range(1,11))
t=[x for x in l if x%2==0]
t

[2, 4, 6, 8, 10]

44. Write a program which accepts a string as input to print "Yes" if the string is "yes" or "YES" or "Yes", otherwise print "No".
Hints: Use if statement to judge condition.


In [68]:
s=input()
if s=="yes" or s=="YES" or s=="Yes":
    print('yes')
else:
    print('no')


yes
yes


45. Write a program which can filter even numbers in a list by using filter function. The list is: [1,2,3,4,5,6,7,8,9,10].
Hints: use filter() to filter some elements in a list. Use lambda to define anonymous functions.


In [69]:
l=range(1,11)
evenNumbers = list(filter(lambda x: x%2==0, l))
print(evenNumbers)

[2, 4, 6, 8, 10]


46. Write a program which can map() to make a list whose elements are square of elements in [1,2,3,4,5,6,7,8,9,10].
Hints: Use map() to generate a list. Use lambda to define anonymous functions.


In [70]:
li = [1,2,3,4,5,6,7,8,9,10]
squaredNumbers = list(map(lambda x: x**2, li))
print(squaredNumbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


47. Write a program which can map() and filter() to make a list whose elements are square of even number in [1,2,3,4,5,6,7,8,9,10].
Hints: Use map() to generate a list. Use filter() to filter elements of a list. Use lambda to define anonymous functions.


In [71]:
l=range(1,11)
even=filter(lambda x:x%2==0,l)
esq=list(map(lambda x:x**2,even))
esq

[4, 16, 36, 64, 100]

48. Write a program which can filter() to make a list whose elements are even number between 1 and 20 (both included).
Hints: Use filter() to filter elements of a list. Use lambda to define anonymous functions.


In [72]:
l=range(1,21)
evenNumbers = list(filter(lambda x: x%2==0, l))
print(evenNumbers)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


49. Write a program which can map() to make a list whose elements are square of numbers between 1 and 20 (both included).
Hints: Use map() to generate a list. Use lambda to define anonymous functions.


In [73]:
li=range(1,21)
squaredNumbers = list(map(lambda x: x**2, li))
print(squaredNumbers)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


50. Define a class named American which has a static method called printNationality.
Hints: Use @staticmethod decorator to define class static method.


In [74]:
class American(object):
    @staticmethod
    def printNationality():
        print("America")

anAmerican = American()
anAmerican.printNationality()
American.printNationality()

America
America


51. Define a class named American and its subclass NewYorker.
Hints: Use class Subclass(ParentClass) to define a subclass.


In [75]:
class American(object):
    pass

class NewYorker(American):
    pass
a=American()
b=NewYorker()
print(a,b)


<__main__.American object at 0x0000019CF81F8278> <__main__.NewYorker object at 0x0000019CF81F85F8>


52. Define a class named Circle which can be constructed by a radius. The Circle class has a method which can compute the area.
Hints: Use def methodName(self) to define a method.


In [76]:
class Circle:
    def __init__(self):
        pass
    def area(self,n):
        print(2*3.14*n)
c=Circle()
c.area(1)

6.28


53. Define a class named Rectangle which can be constructed by a length and width. The Rectangle class has a method which can compute the area.
Hints: Use def methodName(self) to define a method.


In [77]:
class Rectangle:
    def __init__(self):
        pass
    def area(self,l,b):
        print(l*b)
r=Rectangle()
r.area(2,3)

6


54. Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have a area function which can print the area of the shape where Shape's area is 0 by default.
Hints: To override a method in super class, we can define a method with the same name in the super class.


In [78]:
class Shape:
    def __init__(self,l):
        pass
    def area(self):
        print('0')
class Square(Shape):
    def __init__(self,l):
        self.length=l
    def area(self):
        l=self.length
        print(l*l)
s=Shape(5)
sq=Square(4)
sq.area()

16


55. Write a function to compute 5/0 and use try/except to catch the exceptions.
Hints: Use try/except to catch exceptions.


In [79]:
def comp():
    return 5/0
try:
    comp()
except ZeroDivisionError:
    print("division by zero!")
finally:
    print('In finally block for cleanup')

division by zero!
In finally block for cleanup


56. Define a custom exception class which takes a string message as attribute.
Hints: To define a custom exception, we need to define a class inherited from Exception.


In [12]:
class Error(Exception):
    def __init__(self,m):
        self.msg=m
        print("error occured:"+self.msg)
e=Error("Somethingnwent wrong")

error occured:Somethingnwent wrong


57. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the user name of a given email address. Both user names and company names are composed of letters only.
If the following email address is given as input to the program: Chandra@analytixlabs.com
Then, the output of the program should be: Chandra
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use \w to match letters.


In [13]:
import re
emailAddress = input()
pat2 = "(\w+)@((\w+\.)+(com))"
r2 = re.match(pat2,emailAddress)
print(r2.group(1))

paras@gmail.com
paras


58. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the company name of a given email address. Both user names and company names are composed of letters only.
If the following email address is given as input to the program: Chandra@analytixlabs.com
Then, the output of the program should be: analytixlabs
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use \w to match letters


In [14]:
import re
emailAddress = input()
pat2 = "(\w+)@(\w+)\.(com)"
r2 = re.match(pat2,emailAddress)
print(r2.group(2))

paras@gmail.com
gmail


59. Write a program which accepts a sequence of words separated by whitespace as input to print the words composed of digits only.
If the following words are given as input to the program: 2 cats and 3 dogs.
Then, the output of the program should be: ['2', '3']
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use re.findall() to find all substring using regex.


In [15]:
import re
s=input()
l=re.findall('\d+',s)
print(l)

2 cats and 3 dogs
['2', '3']


60. Print a unicode string "hello world".
Hints: Use u'strings' format to define unicode string.


In [16]:
s=u'Hello world'
print(s)

Hello world


61. Write a program to read an ASCII string and to convert it to a unicode string encoded by utf-8.
Hints: Use unicode() function to convert.


In [17]:
s=input()
s.encode('utf-8')
print(s)

hello world
hello world


62. Write a special comment to indicate a Python source code file is in unicode.


In [18]:
# -*- coding: utf-8 -*-



63. Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).
If the following n is given as input to the program: 5
Then, the output of the program should be: 3.55
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: Use float() to convert an integer to a floa

In [20]:
n=int(input())
sum=0.0
for i in range(1,n+1):
    sum += float(float(i)/(i+1))
print(round(sum,2))

5
3.55


64. Write a program to compute:
f(n)=f(n-1)+100 when n>0
and f(0)=1
with a given n input by console (n>0).
If the following n is given as input to the program: 5
Then, the output of the program should be: 500
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: We can define recursive function in Python.


In [21]:
 def f(n):
    if n==0:
        return 0
    else:
        return f(n-1)+100
n=int(input())
print(f(n))

5
500


65. The Fibonacci sequence is computed based on the following formula:
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1
Please write a program to compute the value of f(n) with a given n input by console.
If the following n is given as input to the program: 7
Then, the output of the program should be: 13
In case of input data being supplied to the question, it should be assumed to be a console input.
Hints: We can define recursive function in Python.


In [22]:
def f(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return f(n-1)+f(n-2)
n=int(input())
print(f(n))

7
13


66. The Fibonacci sequence is computed based on the following formula:
f(n)=0 if n=0
f(n)=1 if n=1
f(n)=f(n-1)+f(n-2) if n>1

Please write a program using list comprehension to print the Fibonacci sequence in comma separated form with a given n input by console.
If the following n is given as input to the program: 7
Then, the output of the program should be: 0, 1, 1, 2, 3, 5, 8, 13
Hints: We can define recursive function in Python. Use list comprehension to generate a list from an existing list. Use string.join() to join a list of strings. In case of input data being supplied to the question, it should be assumed to be a console input.

In [24]:
def f(n):
    if n == 0: return 0
    elif n == 1: return 1
    else: return f(n-1)+f(n-2)

n=int(input())
values =[int(f(x)) for x in range(0, n+1)]
values

7


[0, 1, 1, 2, 3, 5, 8, 13]

67. Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console.
Example: If the following n is given as input to the program: 10
Then, the output of the program should be: 0,2,4,6,8,10
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the question, it should be assumed to be a console input.


In [25]:
def EvenGenerator(n):
    i=0
    while i<=n:
        if i%2==0:
            yield i
        i+=1


n=int(input())
values = []
for i in EvenGenerator(n):
    values.append(int(i))
print(values)

10
[0, 2, 4, 6, 8, 10]


68. Please write a program using generator to print the numbers which can be divisible by 5 and 7 between 0 and n in comma separated form while n is input by console.
If the following n is given as input to the program: 100
Then, the output of the program should be: 0, 35, 70
Hints: Use yield to produce the next value in generator. In case of input data being supplied to the question, it should be assumed to be a console input.


In [26]:
def NumGenerator(n):
    for i in range(n+1):
        if i%5==0 and i%7==0:
            yield i

n=int(input())
values = []
for i in NumGenerator(n):
    values.append(int(i))
print(values)

100
[0, 35, 70]



69. Please write assert statements to verify that every number in the list [2,4,6,8] is even.
Hints: Use "assert expression" to make assertion.


In [27]:
li = [2,4,6,8]
for i in li:
    assert i%2==0

70. Please write a program which accepts basic mathematic expression from console and print the evaluation result.
If the following string is given as input to the program: 35+3
Then, the output of the program should be: 38
Hints: Use eval() to evaluate an expression.


In [28]:
s=input()
print(eval(s))

35+3
38


71. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions.

In [30]:
import math
def bin_search(li, element):
    bottom = 0
    top = len(li)-1
    index = -1
    while top>=bottom and index==-1:
        mid = int(math.floor((top+bottom)/2.0))
        if li[mid]==element:
            index = mid
        elif li[mid]>element:
            top = mid-1
        else:
            bottom = mid+1

    return index

li=[2,5,7,9,11,17,222]
print('index:',bin_search(li,7))

index: 2


72. Please write a binary search function which searches an item in a sorted list. The function should return the index of element to be searched in the list.
Hints: Use if/elif to deal with conditions.


In [32]:
import math
def bin_search(li, element):
    bottom = 0
    top = len(li)-1
    index = -1
    while top>=bottom and index==-1:
        mid = int(math.floor((top+bottom)/2.0))
        if li[mid]==element:
            index = mid
        elif li[mid]>element:
            top = mid-1
        else:
            bottom = mid+1

    return index

li=[2,5,7,9,11,17,222]
print('index:',bin_search(li,17))

index: 5


73. Please generate a random float where the value is between 10 and 100 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].


In [43]:
import random
#0*90+10=10
#1*90+10=100
print(random.random()*90+10)
print(random.randrange(10,100))

83.60549299678814
30


74. Please generate a random float where the value is between 5 and 95 using Python math module.
Hints: Use random.random() to generate a random float in [0,1].


In [44]:
import random

# 0*90 + 5 =5
# 1*90 + 5 =95
print(random.random()*90+5)

70.02205997965928


75. Please write a program to output a random even number between 0 and 10 inclusive using random module and list comprehension.
Hints: Use random.choice() to a random element from a list.


In [45]:
import random
print(random.choice([i for i in range(11) if i%2==0]))

2


76. Please write a program to output a random number, which is divisible by 5 and 7, between 0 and 10 inclusive using random module and list comprehension.
Hints: Use random.choice() to a random element from a list.


In [46]:
import random
print(random.choice([i for i in range(201) if i%5==0 and i%7==0]))

35


77. Please write a program to generate a list with 5 random numbers between 100 and 200 inclusive.
Hints: Use random.sample() to generate a list of random values.


In [47]:
import random
print(random.sample(range(100,201), 5))

[177, 199, 187, 135, 101]


78. Please write a program to randomly generate a list with 5 even numbers between 100 and 200 inclusive.
Hints: Use random.sample() to generate a list of random values.


In [49]:
import random
print(random.sample([i for i in range(100,201) if i%2==0], 5))

[108, 178, 176, 110, 148]


79. Please write a program to randomly generate a list with 5 numbers, which are divisible by 5 and 7 , between 1 and 1000 inclusive.
Hints: Use random.sample() to generate a list of random values.


In [50]:
import random
print(random.sample([i for i in range(1,1001) if i%5==0 and i%7==0],5))

[280, 560, 665, 455, 630]


80. Please write a program to randomly print a integer number between 7 and 15 inclusive.
Hints: Use random.randrange() to a random integer in a given range.


In [51]:
import random
print(random.randrange(7,16))

13


81. Please write a program to compress and decompress the string "hello world!hello world!hello world!hello world!".
Hints: Use zlib.compress() and zlib.decompress() to compress and decompress a string.

In [54]:
import zlib
s = 'hello world!hello world!hello world!hello world!'
s=s.encode()
t = zlib.compress(s)
print(t)
print(zlib.decompress(t))

b'x\x9c\xcbH\xcd\xc9\xc9W(\xcf/\xcaIQ\xcc \x82\r\x00\xbd[\x11\xf5'
b'hello world!hello world!hello world!hello world!'


82. Please write a program to print the running time of execution of "1+1" for 100 times.
Hints: Use timeit() function to measure the running time.


In [55]:
from timeit import Timer
t = Timer("for i in range(100):1+1")
print(t.timeit())

6.288926175014149


83. Please write a program to shuffle and print the list [3,6,7,8].
Hints: Use shuffle() function to shuffle a list.


In [57]:
from random import shuffle
li = [3,6,7,8]
shuffle(li)
print(li)

[6, 3, 8, 7]


84. Please write a program to shuffle and print the list [3,6,7,8].
Hints: Use shuffle() function to shuffle a list.


In [58]:
from random import shuffle
li = [3,6,7,8]
shuffle(li)
print(li)

[8, 7, 6, 3]


85. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in ["Play", "Love"] and the object is in ["Hockey","Football"].
Hints: Use list[index] notation to get a element from a list.


In [59]:
subjects=["I", "You"]
verbs=["Play", "Love"]
objects=["Hockey","Football"]
for i in range(len(subjects)):
    for j in range(len(verbs)):
        for k in range(len(objects)):
            sentence = "%s %s %s." % (subjects[i], verbs[j], objects[k])
            print(sentence)

I Play Hockey.
I Play Football.
I Love Hockey.
I Love Football.
You Play Hockey.
You Play Football.
You Love Hockey.
You Love Football.


86. Please write a program to print the list after removing delete even numbers in [5,6,77,45,22,12,24].
Hints: Use list comprehension to delete a bunch of element from a list.


In [60]:
l=[5,6,77,45,22,12,24]
l= [x for x in l if x%2!=0]
print(l)

[5, 77, 45]


87. By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list.


In [61]:
li = [12,24,35,70,88,120,155]
li = [x for x in li if x%5!=0 and x%7!=0]
print(li)

[12, 24, 88]


88. By using list comprehension, please write a program to print the list after removing the 0th, 2nd, 4th,6th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.


In [62]:
li = [12,24,35,70,88,120,155]
li = [x for (i,x) in enumerate(li) if i%2!=0]
print(li)

[24, 70, 120]


89. By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0.
Hints: Use list comprehension to make an array.


In [63]:
array = [[ [0 for col in range(8)] for col in range(5)] for row in range(3)]
print(array)

[[[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], [[0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]]]


In [64]:
array

[[[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]],
 [[0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0]]]

90. By using list comprehension, please write a program to print the list after removing the 0th,4th,5th numbers in [12,24,35,70,88,120,155].
Hints: Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple.


In [65]:
li = [12,24,35,70,88,120,155]
li = [x for (i,x) in enumerate(li) if i not in (0,4,5)]
print(li)

[24, 35, 70, 155]


91. By using list comprehension, please write a program to print the list after removing the value 24 in [12,24,35,24,88,120,155].
Hints: Use list's remove method to delete a value.

In [66]:

li = [12,24,35,24,88,120,155]
li = [x for x in li if x!=24]
print(li)

[12, 35, 88, 120, 155]


92. With two given lists [1,3,6,78,35,55] and [12,24,35,24,88,120,155], write a program to make a list whose elements are intersection of the above given lists.
Hints: Use set() and "&=" to do set intersection operation.


In [67]:
set1=set([1,3,6,78,35,55])
set2=set([12,24,35,24,88,120,155])
set1 &= set2
li=list(set1)
print(li)

[35]


93. With a given list [12, 24, 35, 24, 88, 120, 155, 88, 120, 155], write a program to print this list after removing all duplicate values with original order reserved.
Hints: Use set() to store a number of values without duplicate.


In [68]:
l=[12, 24, 35, 24, 88, 120, 155, 88, 120, 155]
print(set(l))

{35, 12, 155, 24, 88, 120}


94. Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class.
Hints: Use Subclass(Parentclass) to define a child class.


In [69]:
class Person(object):
    def getGender( self ):
        return "Unknown"

class Male( Person ):
    def getGender( self ):
        return "Male"

class Female( Person ):
    def getGender( self ):
        return "Female"

aMale = Male()
aFemale= Female()
print(aMale.getGender())
print(aFemale.getGender())

Male
Female


95. Please write a program which count and print the numbers of each character in a string input by console.
If the following string is given as input to the program: abcdefgabc
Then, the output of the program should be:
a,2
c,2
b,2
e,1
d,1
g,1
f,1
Hints: Use dict to store key/value pairs. Use dict.get() method to lookup a key with default value.


In [74]:
dic = {}
#s=input()
s='abcdefgabc'
for s in s:
    dic[s] = dic.get(s,0)+1
print('\n'.join(['%s,%s' % (k, v) for k, v in dic.items()]))

a,2
b,2
c,2
d,1
e,1
f,1
g,1


96. Please write a program which accepts a string from console and print it in reverse order.
If the following string is given as input to the program: rise to vote sir
Then, the output of the program should be: ris etov ot esir
Hints: Use list[::-1] to iterate a list in a reverse order.


In [75]:
#s=input()
s='rise to vote sir'
print(s[::-1])

ris etov ot esir


97. Please write a program which accepts a string from console and print the characters that have even indexes.
If the following string is given as input to the program: H1e2l3l4o5w6o7r8l9d
Then, the output of the program should be: Helloworld
Hints: Use list[::2] to iterate a list by step 2.


In [76]:
#s=input()
s='H1e2l3l4o5w6o7r8l9d'
print(s[::2])

Helloworld


98. Please write a program which prints all permutations of [1, 2, 3]
Hints: Use itertools.permutations() to get permutations of list.


In [77]:
import itertools
print(list(itertools.permutations([1,2,3])))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


99. Write a program to solve a classic ancient Chinese puzzle:
We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?
Hint: Use for loop to iterate all possible solutions


In [78]:
def solve(numheads,numlegs):
    ns='No solutions!'
    for i in range(numheads+1):
        j=numheads-i
        if 2*i+4*j==numlegs:
            return i,j
    return ns,ns

numheads=35
numlegs=94
solutions=solve(numheads,numlegs)
print(solutions)


(23, 12)


100. Create a dictionary with phone numbers (phonebook = {“John”: 938477566, "Jack”: 938377264, "Jill”: 947662781}). Add "Jake" to the phonebook with the phone number 938273443, and remove Jill from the phonebook.

In [79]:
phonebook = {"John": 938477566, "Jack": 938377264, "Jill": 947662781}
phonebook["Jake"]='938273443'
phonebook

{'John': 938477566, 'Jack': 938377264, 'Jill': 947662781, 'Jake': '938273443'}